# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6b5dc1843b2a7022879b29dfd5d4a20a6f0eaeff5cb873c54dcf654106ce00c82dc29cf018c22968987cdb50788f757db1c2b7160010599300c7fa65896d6f8

test:
  secret_key_base: c975f13f6e65eb0ad91fd98be84bdd9793c22f257bc118ada95e2ab5e1030afd9fd4f0426118dca67696e8d6aedb631ec0097153dee226fe3a4c9ad72a406983

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
